# Settings
baseurl: /aws
permalink: /:categories/:title

# About
title: AWS
tagline: Applications Web et Sécurité
authors:
  - name: Luca De Feo
    url: 'http://defeo.lu/'
created: 2013
license:
  name: Creative Commons 4.0 Attribution-ShareAlike
  shortname: CC-BY-SA 4.0
  url: http://creativecommons.org/licenses/by-sa/4.0/
  badge: http://i.creativecommons.org/l/by-sa/4.0/80x15.png

# Display a log in the top bar
#logo: assets/logo/eLeMentS.svg

# Display a GitHub fork me logo in the lower right corner
forkme: yes

# Default configuration for pages.
# Can be used to activate addons on all pages.
defaults:
  - scope:
      path: ''
    values:
      layout: default
      addons:
        highlightjs: yes
        clicker:
          host: http://keats.prism.uvsq.fr
          methods: 
            - title: " @UVSQ"
              icon: graduation-cap,
              path: /login/saml,
          messages:
            loginError: Veulliez vous connecter pour visualiser ce questionnaire.
            unknownError: "Une erreur s'est produite, veuillez réessayer."
            submitError: "Impossible d'envoyer le questionnaire, veuillez réessayer."
            submit: "Envoyer réponse"
  - scope:
      path: lessons
    values:
      addons:
        slideshow: { width: 1066, height: 600 }
        style_goodies: yes
  - scope:
      path: tutorials
    values:
      layout: article
      addons:
        style_goodies: yes
        
# New page / post / etc. menu
#create:
#  pages: yes
#  collections:
#    - key: posts
#      template: Write something
#    - key: tutorial
#      template: Write a tutorial

collections:
  addons:
    output: true
  projects:
  lessons: 
    output: true
    name: Leçons
  tutorials:
    name: TDs
    output: true

# Kramdown configuration (markdown parser)
kramdown:
  parse_block_html: true

# Prose.io configuration, if that's your style
#prose: no

# SASS configuration.
# Better not touch this
sass:
  sass_dir: assets/css
  style: compressed
