baseurl: /aws
permalink: /:categories/:title

kramdown:
  parse_block_html: true

collections:
  projects:
  lessons: 
    output: true
    name: Leçons
  tutorials:
    name: TDs
    output: true
  
